buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'io.github.jumosqu12.screenplayarchitecture' version '2.0.1'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.1.14'
    id 'java'
    id 'eclipse'
    id 'idea'
}

group 'com.fabrica.screenplay'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '4.1.14'
    serenityCucumberVersion = '4.1.14'
    lombokVersion = '1.18.36'
    junit = '4.13.2'
    hamcrest = '1.3'
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-junit:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-screenplay:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-screenplay-rest:$rootProject.ext.serenityVersion"
    implementation "net.serenity-bdd:serenity-cucumber:$rootProject.ext.serenityCucumberVersion"
    implementation 'org.slf4j:slf4j-simple:2.0.16'
    implementation 'io.rest-assured:rest-assured:5.5.0'
    implementation 'com.google.code.gson:gson:2.11.0'

    testImplementation "junit:junit:$rootProject.ext.junit"
    testImplementation "org.hamcrest:hamcrest-all:$rootProject.ext.hamcrest"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
}

test {
    useJUnit()
    testLogging {
        showStandardStreams = true
    }
    outputs.upToDateWhen { false }
}
