serenity {
    take.screenshots = FOR_FAILURES
    use.unique.browser = true
    test.root = com.fabrica.screenplay
    console.colors = true
    report {
        accessibility = true
    }
    requirement {
        types = "epic, feature"
    }
}

rest {
    default {
        baseUrl = "http://localhost:8080"
    }
}
